core/StringLanguage.al
core/AppHead.al
core/AppLayout.al
core/AppSettingsStorage.al
core/ActivityManager.al

core/ui/header.co
core/ui/headerbutton.co
core/ui/headertext.co
core/ui/icon.co

app/res/style.co
app/res/manifest.co

app/res/strings/en-GB.co

app/res/layouts/MainActivity.co

app/scripts/MainActivity.al

core/Core.al